Updated setup and rst

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,6 +1,17 @@
 #!/bin/bash
+
+#Checking for installation of xautomation
+if ! [ -x "$(command -v xte)" ]; then
+  echo 'Xautomation is not installed and is required, installing xautomation.'
+  apt-get install xautomation
+  exit 1
+fi
+
+#Local File Assumption
 file_local=0
 file="rst"
+
+#If local file then moving to /usr/bin
 if [ -f "$file" ]; then
 	chmod +x rst
 	echo "RST file found locally moving to /usr/bin"
@@ -8,7 +19,12 @@ if [ -f "$file" ]; then
   	rm /usr/bin/rst
   	cp rst /usr/bin/rst
   	chmod +x /usr/bin/rst
+
+#No local file, wgetting for repo and putting in /usr/bin
 else
+	if [ -f "/usr/bin/rst" ]; then
+		rm /usr/bin/rst
+	fi
 	wget https://raw.githubusercontent.com/mustansirgodhrawala/rst/master/rst?token=GHSAT0AAAAAABQO6HOHF3FRX2HHMWROWNQAYQIIHZA
 	mv rst /usr/bin/rst
 	chmod +x /usr/bin/rst
